# Generated by Django 4.2.5 on 2023-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderdisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=0, max_length=50)),
                ('Email', models.CharField(default=0, max_length=50)),
                ('City', models.CharField(default=0, max_length=10)),
                ('Address', models.CharField(default=0, max_length=50)),
                ('ZipCode', models.IntegerField(default=0, max_length=10)),
                ('Country', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
