# Generated by Django 4.2.5 on 2023-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdisplay',
            name='ZipCode',
            field=models.IntegerField(default=0),
        ),
    ]
