# Generated by Django 4.2.5 on 2023-09-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_orderdisplay_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderdisplay',
        ),
    ]
